import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/Nav/Nav.css";
import NavContent from "@/components/NavContent/NavContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased app-shell`}
      >
        <main className="main-content">{children}</main>
        <NavContent/>
      </body>
    </html>
  );
}
